import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { StyledEngineProvider } from '@mui/material/styles';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <StyledEngineProvider injectFirst>
        <body className='bg-neutral-950 h-screen'>{children}</body>
      </StyledEngineProvider>
    </html>
  );
}
